### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by LavMehta** [kromerm/adfdataflowdocs#11]
Hi kromerm, 
I am facing following error when performing a data transformation action using ADF, please if you could just give a hint on what needs to be corrected. 

"code":"BadRequest","message":"ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression '_c1'","target":"pipeline/pipeline1/runid/########","details":null,"error":null}

Thanks in Advance
Lav

**Comment by kromerm** [comment]
Hi Lav - Can you please go into the ADF browser UI and click on the feedback icon (smiley face) from the top-right?  Enter into there the name of your data factory and this error so that we can route it to the proper engineer for inspection.   Thanks!

**Comment by LavMehta** [comment]
Thanks kromerm , 
I Submitted the problem ,now waiting for the answer. 
thanks for your reply , i didn't expected that Profi like you and others would reply to such beginners problem ,, but you did ,, and i am really thankful to you. 
Regards
Lav

**Comment by LavMehta** [comment]
Thanks kromerm , 
I Submitted the problem ,now waiting for the answer. 
thanks for your reply , i didn't expected that Profi like you and others would reply to such beginners problem ,, but you did ,, and i am really thankful to you. 
Regards
Lav

**Comment by LavMehta** [comment]
Thanks kromerm , 
I Submitted the problem ,now waiting for the answer. 
thanks for your reply , i didn't expected that Profi like you and others would reply to such beginners problem ,, but you did ,, and i am really thankful to you. 
Regards
Lav
