### ISSUE TITLE
Read All Files From Folder issue

### ISSUE THREAD

**Issue by B4PJS** [kromerm/adfdataflowdocs#4]
When reading all files from a folder, the default behaviour for ADF is to leave the file name blank. This causes an issue in a data flow, as you need to specify a * wildcard else it will not be able to read the files when debugging or running from a pipeline.

**Comment by kromerm** [comment]
We are fixing this with new updates to the file-based datasets that will land in 1-2 months from now. Look for updates on the status of these.

**Comment by kromerm** [comment]
Closing as fix is planned
